services:
  jenkins:
    container_name: "jenkins"
    image: "jenkins/docker"
    build:
      context: "./pipeline"
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - "net"

  remote_host:
    container_name: "remote-host"
    image: "remote-host"
    build:
      context: "./ubuntu"
    volumes:
      - "$PWD/aws-s3.sh:/tmp/script.sh"
    networks:
      - "net"

  git:
    image: "gitlab/gitlab-ce:latest"
    container_name: "git-server"
    hostname: "gitlab.local.com"
    restart: "always"
    ports:
      - "8090:80"
    volumes:
      - "$GITLAB_HOME/config:/etc/gitlab"
      - "$GITLAB_HOME/logs:/var/log/gitlab"
      - "$GITLAB_HOME/data:/var/opt/gitlab"
    shm_size: "256m"
    networks:
      - "net"

networks:
  net:

